spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/hello
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  jooq:
    sql-dialect: POSTGRES

server:
  port: 8080
