CREATE TABLE IF NOT EXISTS problem (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(255) NOT NULL,
    spec_md TEXT         NOT NULL,
    slug    VARCHAR(255),
    active  BOOLEAN      NOT NULL DEFAULT TRUE
);
-- GitLab 동기화 이전에 만들어진 DB를 위한 마이그레이션.
ALTER TABLE problem ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE problem ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
-- 시더 시절 하드코딩 문제를 GitLab 디렉토리명으로 백필한다(신규 DB에선 no-op).
UPDATE problem SET slug = 'hello-world'     WHERE slug IS NULL AND title = 'Hello World 출력';
UPDATE problem SET slug = 'print-ssafy'     WHERE slug IS NULL AND title = 'SSAFY 출력';
UPDATE problem SET slug = 'welcome-message' WHERE slug IS NULL AND title = '환영 메시지 출력';
CREATE UNIQUE INDEX IF NOT EXISTS uq_problem_slug ON problem (slug);

CREATE TABLE IF NOT EXISTS problem_file (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT       NOT NULL REFERENCES problem (id) ON DELETE CASCADE,
    ordinal    INT          NOT NULL,
    path       VARCHAR(500) NOT NULL,
    content    TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_problem_file_problem ON problem_file (problem_id, ordinal);

-- 채점용 테스트. problem_file과 분리해야 노출 경로(ProblemView)에 딸려 가지 않는다.
CREATE TABLE IF NOT EXISTS problem_test_file (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT       NOT NULL REFERENCES problem (id) ON DELETE CASCADE,
    ordinal    INT          NOT NULL,
    path       VARCHAR(500) NOT NULL,
    content    TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_problem_test_file_problem ON problem_test_file (problem_id, ordinal);

-- 테스트 분리 이전에 동기화된 DB를 위한 마이그레이션.
-- 그때는 skeleton/src/test/** 가 그대로 problem_file에 들어가 사용자에게 노출됐다.
-- 재동기화를 강제하는 나머지 절반은 sync_state가 만들어진 뒤에 있다(이 파일 맨 아래).
DELETE FROM problem_file WHERE path LIKE 'src/test/%';

CREATE TABLE IF NOT EXISTS attempt (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT      NOT NULL REFERENCES problem (id),
    status     VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    feedback   TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE
);
-- 제출 기능 이전에 만들어진 DB를 위한 마이그레이션.
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS';
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS feedback TEXT;
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS attempt_file (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT       NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    ordinal    INT          NOT NULL,
    path       VARCHAR(500) NOT NULL,
    content    TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_attempt_file_attempt ON attempt_file (attempt_id, ordinal);

CREATE TABLE IF NOT EXISTS attempt_turn (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id  BIGINT NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    ordinal     INT    NOT NULL,
    user_prompt TEXT   NOT NULL,
    ai_summary  TEXT   NOT NULL,
    feedback    TEXT
);
-- 턴별 피드백 이전에 만들어진 DB를 위한 마이그레이션. 그때 제출된 어템프트는 attempt.feedback만 갖는다.
ALTER TABLE attempt_turn ADD COLUMN IF NOT EXISTS feedback TEXT;
-- 중복 요청이 같은 턴을 두 번 쌓는 것을 막는 안전망.
-- 기존 DB에는 옛 인덱스 idx_attempt_turn_attempt가 남아 있을 수 있다(무해). 필요하면 수동으로 DROP INDEX 한다.
CREATE UNIQUE INDEX IF NOT EXISTS uq_attempt_turn_attempt_ordinal ON attempt_turn (attempt_id, ordinal);

CREATE TABLE IF NOT EXISTS turn_file_change (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id     BIGINT       NOT NULL REFERENCES attempt_turn (id) ON DELETE CASCADE,
    ordinal     INT          NOT NULL,
    path        VARCHAR(500) NOT NULL,
    change_type VARCHAR(20)  NOT NULL,
    content     TEXT
);
-- 턴별 변경 후 코드 저장 이전에 만들어진 DB를 위한 마이그레이션. DELETED는 남은 내용이 없어 NULL이다.
-- 기존 어템프트 데이터는 attempt_file이 head였던 옛 의미라 새 의미(불변 base)와 충돌하고 턴별 코드도 복원할 수 없다.
-- 그런 DB에서는 수동으로 한 번 TRUNCATE attempt CASCADE 한다.
ALTER TABLE turn_file_change ADD COLUMN IF NOT EXISTS content TEXT;
CREATE INDEX IF NOT EXISTS idx_turn_file_change_turn ON turn_file_change (turn_id, ordinal);

CREATE TABLE IF NOT EXISTS turn_tool_call (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id BIGINT       NOT NULL REFERENCES attempt_turn (id) ON DELETE CASCADE,
    ordinal INT          NOT NULL,
    tool    VARCHAR(50)  NOT NULL,
    path    VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_turn_tool_call_turn ON turn_tool_call (turn_id, ordinal);

-- LLM API 호출 1건 = 1행. 원본 행이 진실이고 합계는 조회 시 SUM으로 파생한다.
-- 턴 연결은 (attempt_id, turn_ordinal)로 한다 — 턴이 저장되지 않은 실패 호출도 남겨야 하기 때문이다.
CREATE TABLE IF NOT EXISTS attempt_llm_call (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id          BIGINT      NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    turn_ordinal        INT,                       -- 피드백 호출·실패 flush 행은 NULL
    purpose             VARCHAR(20) NOT NULL,      -- CODE | FEEDBACK
    seq                 INT         NOT NULL,      -- 호출 순번(라운드). FAILED 마커는 마지막 성공 seq+1
    model               VARCHAR(100),              -- FAILED 마커 행은 NULL
    input_tokens        BIGINT,
    output_tokens       BIGINT,
    cached_input_tokens BIGINT,
    reasoning_tokens    BIGINT,
    latency_ms          BIGINT,
    cost                DECIMAL(14,8),             -- USD, 쓰기 시점 단가 스냅샷. 미등록 모델 NULL
    status              VARCHAR(20) NOT NULL,      -- SUCCESS | FAILED
    error_type          VARCHAR(50),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_attempt_llm_call_attempt ON attempt_llm_call (attempt_id, turn_ordinal, seq);

-- 실패한 CODE 호출의 사용자 프롬프트. 실패하면 턴이 저장되지 않아 입력이 어디에도 남지 않는다.
-- FEEDBACK 실패 행이 NULL인 것은 기록 누락이 아니다 — 피드백 프롬프트는 사용자가 타이핑한 값이 아니라
-- 어댑터가 problem과 attempt로 만들어내는 산출물이고, 그 입력은 어템프트에 그대로 남아 있다.
ALTER TABLE attempt_llm_call ADD COLUMN IF NOT EXISTS user_prompt TEXT;

-- 로그인 기능: 사용자 계정. 테이블명은 user가 PostgreSQL 예약어라 users를 사용한다.
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30)              NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    nickname      VARCHAR(30)              NOT NULL,
    email         VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
-- 중복 가입 방지의 최종 안전망(서비스 계층 검사와 별개로 DB가 보장).
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (email);

-- 기존 어템프트는 소유자를 알 수 없으므로 NULL로 남기고, 새 코드가 생성하는 어템프트에는 user_id가 필수다.
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE attempt DROP CONSTRAINT IF EXISTS fk_attempt_user;
ALTER TABLE attempt ADD CONSTRAINT fk_attempt_user FOREIGN KEY (user_id) REFERENCES users (id);
CREATE INDEX IF NOT EXISTS idx_attempt_user ON attempt (user_id, id);
CREATE INDEX IF NOT EXISTS idx_attempt_user_submitted ON attempt (user_id, status, submitted_at DESC, id DESC);

-- 비로그인 풀이의 소유자. 쿠키 원문은 저장하지 않고 SHA-256 해시만 저장한다.
CREATE TABLE IF NOT EXISTS guest_session (
    id         UUID PRIMARY KEY,
    token_hash VARCHAR(64)              NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_guest_session_token_hash ON guest_session (token_hash);
CREATE INDEX IF NOT EXISTS idx_guest_session_expires_at ON guest_session (expires_at);

ALTER TABLE attempt ADD COLUMN IF NOT EXISTS guest_session_id UUID;
ALTER TABLE attempt DROP CONSTRAINT IF EXISTS fk_attempt_guest_session;
ALTER TABLE attempt ADD CONSTRAINT fk_attempt_guest_session
    FOREIGN KEY (guest_session_id) REFERENCES guest_session (id);
CREATE INDEX IF NOT EXISTS idx_attempt_guest_session ON attempt (guest_session_id, id);
-- 기존 배포 DB의 소유자 없는 과거 attempt 때문에 NOT VALID로 추가한다.
-- 새로 INSERT/UPDATE되는 행에는 즉시 적용되며, 과거 행을 초기화한 뒤 VALIDATE 할 수 있다.
ALTER TABLE attempt DROP CONSTRAINT IF EXISTS chk_attempt_exactly_one_owner;
ALTER TABLE attempt ADD CONSTRAINT chk_attempt_exactly_one_owner
    CHECK ((user_id IS NOT NULL AND guest_session_id IS NULL)
        OR (user_id IS NULL AND guest_session_id IS NOT NULL)) NOT VALID;

-- 어템프트 코드의 빌드/실행 요청 한 건. 결과는 buildandtest 워커가 큐로 돌려준 것을 반영한다.
CREATE TABLE IF NOT EXISTS code_run (
    id          UUID PRIMARY KEY,
    attempt_id  BIGINT      NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    -- 어느 턴의 코드를 실행했는지. attempt_turn.ordinal과 같은 0-based 값이고,
    -- 턴을 하나도 적용하지 않은 스켈레톤 원본을 실행했으면 NULL이다.
    turn_ordinal INT,
    status      VARCHAR(20) NOT NULL,
    exit_code   INT,
    stdout      TEXT,
    stderr      TEXT,
    duration_ms BIGINT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE
);
-- 턴 단위 실행 이전에 만들어진 DB를 위한 마이그레이션.
-- 그때 실행된 행은 어느 턴이었는지 복원할 수 없어 NULL로 남는다.
ALTER TABLE code_run ADD COLUMN IF NOT EXISTS turn_ordinal INT;
CREATE INDEX IF NOT EXISTS idx_code_run_attempt ON code_run (attempt_id, created_at DESC);
-- 어템프트당 미완료 run은 하나만 허용한다. 동시 요청 레이스를 DB가 막아주는 안전망.
CREATE UNIQUE INDEX IF NOT EXISTS uq_code_run_active ON code_run (attempt_id) WHERE status = 'QUEUED';

CREATE TABLE IF NOT EXISTS idempotency_record (
    idempotency_key VARCHAR(128) PRIMARY KEY,
    user_id         BIGINT REFERENCES users (id),
    guest_session_id UUID REFERENCES guest_session (id),
    attempt_id      BIGINT REFERENCES attempt (id) ON DELETE CASCADE,
    status          VARCHAR(20)              NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
ALTER TABLE idempotency_record ALTER COLUMN idempotency_key TYPE VARCHAR(128);
ALTER TABLE idempotency_record ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE idempotency_record DROP CONSTRAINT IF EXISTS fk_idempotency_record_user;
ALTER TABLE idempotency_record ADD CONSTRAINT fk_idempotency_record_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE idempotency_record ADD COLUMN IF NOT EXISTS guest_session_id UUID;
ALTER TABLE idempotency_record DROP CONSTRAINT IF EXISTS fk_idempotency_record_guest_session;
ALTER TABLE idempotency_record ADD CONSTRAINT fk_idempotency_record_guest_session
    FOREIGN KEY (guest_session_id) REFERENCES guest_session (id);
ALTER TABLE idempotency_record DROP CONSTRAINT IF EXISTS chk_idempotency_exactly_one_owner;
ALTER TABLE idempotency_record ADD CONSTRAINT chk_idempotency_exactly_one_owner
    CHECK ((user_id IS NOT NULL AND guest_session_id IS NULL)
        OR (user_id IS NULL AND guest_session_id IS NOT NULL)) NOT VALID;
CREATE INDEX IF NOT EXISTS idx_idempotency_record_user ON idempotency_record (user_id);
CREATE INDEX IF NOT EXISTS idx_idempotency_record_guest_session ON idempotency_record (guest_session_id);

-- 문제 저장소에서 마지막으로 동기화한 커밋. 한 행(id = 1)만 사용한다.
CREATE TABLE IF NOT EXISTS sync_state (
    id              BIGINT PRIMARY KEY,
    last_commit_sha VARCHAR(64)              NOT NULL,
    synced_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 테스트 분리 마이그레이션의 나머지 절반(problem_test_file 생성부 참고).
-- problem_file에서 테스트를 지워도 problem_test_file로 옮겨오지는 않는다. 동기화는 커밋 SHA가
-- 움직여야 도는데 저장소는 그대로이기 때문이다. SHA를 지워 다음 주기에 전량 재동기화를 강제한다.
-- 테스트가 한 건이라도 들어오면 조건이 거짓이 되어 멈춘다(schema.sql은 부팅마다 실행된다).
-- 문제 저장소에 테스트가 하나도 없으면 매 부팅 재동기화가 도는데, 무해하고 저장소를 고치면 끝난다.
DELETE FROM sync_state WHERE NOT EXISTS (SELECT 1 FROM problem_test_file);
