CREATE TABLE IF NOT EXISTS problem (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(255) NOT NULL,
    spec_md TEXT         NOT NULL,
    slug    VARCHAR(255),
    active  BOOLEAN      NOT NULL DEFAULT TRUE
);
-- GitLab 동기화 이전에 만들어진 DB를 위한 마이그레이션.
ALTER TABLE problem ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE problem ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
-- 시더 시절 하드코딩 문제를 GitLab 디렉토리명으로 백필한다(신규 DB에선 no-op).
UPDATE problem SET slug = 'hello-world'     WHERE slug IS NULL AND title = 'Hello World 출력';
UPDATE problem SET slug = 'print-ssafy'     WHERE slug IS NULL AND title = 'SSAFY 출력';
UPDATE problem SET slug = 'welcome-message' WHERE slug IS NULL AND title = '환영 메시지 출력';
CREATE UNIQUE INDEX IF NOT EXISTS uq_problem_slug ON problem (slug);

CREATE TABLE IF NOT EXISTS problem_file (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT       NOT NULL REFERENCES problem (id) ON DELETE CASCADE,
    ordinal    INT          NOT NULL,
    path       VARCHAR(500) NOT NULL,
    content    TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_problem_file_problem ON problem_file (problem_id, ordinal);

CREATE TABLE IF NOT EXISTS attempt (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT      NOT NULL REFERENCES problem (id),
    status     VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    feedback   TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE
);
-- 제출 기능 이전에 만들어진 DB를 위한 마이그레이션.
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS';
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS feedback TEXT;
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP WITH TIME ZONE;

CREATE TABLE IF NOT EXISTS attempt_file (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT       NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    ordinal    INT          NOT NULL,
    path       VARCHAR(500) NOT NULL,
    content    TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_attempt_file_attempt ON attempt_file (attempt_id, ordinal);

CREATE TABLE IF NOT EXISTS attempt_turn (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id  BIGINT NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    ordinal     INT    NOT NULL,
    user_prompt TEXT   NOT NULL,
    ai_summary  TEXT   NOT NULL,
    feedback    TEXT
);
-- 턴별 피드백 이전에 만들어진 DB를 위한 마이그레이션. 그때 제출된 어템프트는 attempt.feedback만 갖는다.
ALTER TABLE attempt_turn ADD COLUMN IF NOT EXISTS feedback TEXT;
-- 중복 요청이 같은 턴을 두 번 쌓는 것을 막는 안전망.
-- 기존 DB에는 옛 인덱스 idx_attempt_turn_attempt가 남아 있을 수 있다(무해). 필요하면 수동으로 DROP INDEX 한다.
CREATE UNIQUE INDEX IF NOT EXISTS uq_attempt_turn_attempt_ordinal ON attempt_turn (attempt_id, ordinal);

CREATE TABLE IF NOT EXISTS turn_file_change (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id     BIGINT       NOT NULL REFERENCES attempt_turn (id) ON DELETE CASCADE,
    ordinal     INT          NOT NULL,
    path        VARCHAR(500) NOT NULL,
    change_type VARCHAR(20)  NOT NULL,
    content     TEXT
);
-- 턴별 변경 후 코드 저장 이전에 만들어진 DB를 위한 마이그레이션. DELETED는 남은 내용이 없어 NULL이다.
-- 기존 어템프트 데이터는 attempt_file이 head였던 옛 의미라 새 의미(불변 base)와 충돌하고 턴별 코드도 복원할 수 없다.
-- 그런 DB에서는 수동으로 한 번 TRUNCATE attempt CASCADE 한다.
ALTER TABLE turn_file_change ADD COLUMN IF NOT EXISTS content TEXT;
CREATE INDEX IF NOT EXISTS idx_turn_file_change_turn ON turn_file_change (turn_id, ordinal);

CREATE TABLE IF NOT EXISTS turn_tool_call (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id BIGINT       NOT NULL REFERENCES attempt_turn (id) ON DELETE CASCADE,
    ordinal INT          NOT NULL,
    tool    VARCHAR(50)  NOT NULL,
    path    VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_turn_tool_call_turn ON turn_tool_call (turn_id, ordinal);

-- 로그인 기능: 사용자 계정. 테이블명은 user가 PostgreSQL 예약어라 users를 사용한다.
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30)              NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    nickname      VARCHAR(30)              NOT NULL,
    email         VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
-- 중복 가입 방지의 최종 안전망(서비스 계층 검사와 별개로 DB가 보장).
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (email);

-- 기존 어템프트는 소유자를 알 수 없으므로 NULL로 남기고, 새 코드가 생성하는 어템프트에는 user_id가 필수다.
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE attempt DROP CONSTRAINT IF EXISTS fk_attempt_user;
ALTER TABLE attempt ADD CONSTRAINT fk_attempt_user FOREIGN KEY (user_id) REFERENCES users (id);
CREATE INDEX IF NOT EXISTS idx_attempt_user ON attempt (user_id, id);
CREATE INDEX IF NOT EXISTS idx_attempt_user_submitted ON attempt (user_id, status, submitted_at DESC, id DESC);

-- 어템프트 코드의 빌드/실행 요청 한 건. 결과는 buildandtest 워커가 큐로 돌려준 것을 반영한다.
CREATE TABLE IF NOT EXISTS code_run (
    id          UUID PRIMARY KEY,
    attempt_id  BIGINT      NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    status      VARCHAR(20) NOT NULL,
    exit_code   INT,
    stdout      TEXT,
    stderr      TEXT,
    duration_ms BIGINT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_code_run_attempt ON code_run (attempt_id, created_at DESC);
-- 어템프트당 미완료 run은 하나만 허용한다. 동시 요청 레이스를 DB가 막아주는 안전망.
CREATE UNIQUE INDEX IF NOT EXISTS uq_code_run_active ON code_run (attempt_id) WHERE status = 'QUEUED';

CREATE TABLE IF NOT EXISTS idempotency_record (
    idempotency_key VARCHAR(64) PRIMARY KEY,
    user_id         BIGINT REFERENCES users (id),
    attempt_id      BIGINT REFERENCES attempt (id) ON DELETE CASCADE,
    status          VARCHAR(20)              NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
ALTER TABLE idempotency_record ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE idempotency_record DROP CONSTRAINT IF EXISTS fk_idempotency_record_user;
ALTER TABLE idempotency_record ADD CONSTRAINT fk_idempotency_record_user FOREIGN KEY (user_id) REFERENCES users (id);
CREATE INDEX IF NOT EXISTS idx_idempotency_record_user ON idempotency_record (user_id);

-- 문제 저장소에서 마지막으로 동기화한 커밋. 한 행(id = 1)만 사용한다.
CREATE TABLE IF NOT EXISTS sync_state (
    id              BIGINT PRIMARY KEY,
    last_commit_sha VARCHAR(64)              NOT NULL,
    synced_at       TIMESTAMP WITH TIME ZONE NOT NULL
);
