CREATE TABLE IF NOT EXISTS problem (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title   VARCHAR(255) NOT NULL,
    spec_md TEXT         NOT NULL,
    problem_type VARCHAR(20) NOT NULL DEFAULT 'coding',
    -- 채점 언어. 언어별 워커 라우팅과 AI 생성 프롬프트가 이 값을 본다.
    language VARCHAR(20) NOT NULL DEFAULT 'java',
    slug    VARCHAR(255),
    active  BOOLEAN      NOT NULL DEFAULT TRUE
);
-- GitLab 동기화 이전에 만들어진 DB를 위한 마이그레이션.
ALTER TABLE problem ADD COLUMN IF NOT EXISTS slug VARCHAR(255);
ALTER TABLE problem ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE problem ADD COLUMN IF NOT EXISTS problem_type VARCHAR(20) NOT NULL DEFAULT 'coding';
-- 언어 도입 전에 만들어진 DB를 위한 마이그레이션. 그때의 문제는 전부 java였다.
ALTER TABLE problem ADD COLUMN IF NOT EXISTS language VARCHAR(20) NOT NULL DEFAULT 'java';
-- 시더 시절 하드코딩 문제를 GitLab 디렉토리명으로 백필한다(신규 DB에선 no-op).
UPDATE problem SET slug = 'hello-world'     WHERE slug IS NULL AND title = 'Hello World 출력';
UPDATE problem SET slug = 'print-ssafy'     WHERE slug IS NULL AND title = 'SSAFY 출력';
UPDATE problem SET slug = 'welcome-message' WHERE slug IS NULL AND title = '환영 메시지 출력';
CREATE UNIQUE INDEX IF NOT EXISTS uq_problem_slug ON problem (slug);

CREATE TABLE IF NOT EXISTS problem_file (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT       NOT NULL REFERENCES problem (id) ON DELETE CASCADE,
    ordinal    INT          NOT NULL,
    path       VARCHAR(500) NOT NULL,
    content    TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_problem_file_problem ON problem_file (problem_id, ordinal);

-- 채점용 테스트. problem_file과 분리해야 노출 경로(ProblemView)에 딸려 가지 않는다.
CREATE TABLE IF NOT EXISTS problem_test_file (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT       NOT NULL REFERENCES problem (id) ON DELETE CASCADE,
    ordinal    INT          NOT NULL,
    path       VARCHAR(500) NOT NULL,
    content    TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_problem_test_file_problem ON problem_test_file (problem_id, ordinal);

-- 테스트 분리 이전에 동기화된 DB를 위한 마이그레이션.
-- 그때는 skeleton/src/test/** 가 그대로 problem_file에 들어가 사용자에게 노출됐다.
-- 재동기화를 강제하는 나머지 절반은 sync_state가 만들어진 뒤에 있다(이 파일 맨 아래).
DELETE FROM problem_file WHERE path LIKE 'src/test/%';

CREATE TABLE IF NOT EXISTS attempt (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    problem_id BIGINT      NOT NULL REFERENCES problem (id),
    status     VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
    feedback   TEXT,
    pattern_feedback TEXT,
    submitted_at TIMESTAMP WITH TIME ZONE
);
-- 제출 기능 이전에 만들어진 DB를 위한 마이그레이션.
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS';
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS feedback TEXT;
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS submitted_at TIMESTAMP WITH TIME ZONE;
-- pattern 피드백 이전에 제출된 어템프트는 프롬프트 피드백만 갖고 이 값은 NULL이다.
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS pattern_feedback TEXT;

CREATE TABLE IF NOT EXISTS attempt_file (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT       NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    ordinal    INT          NOT NULL,
    path       VARCHAR(500) NOT NULL,
    content    TEXT         NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_attempt_file_attempt ON attempt_file (attempt_id, ordinal);

CREATE TABLE IF NOT EXISTS attempt_turn (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id  BIGINT NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    ordinal     INT    NOT NULL,
    user_prompt TEXT   NOT NULL,
    ai_summary  TEXT   NOT NULL,
    feedback    TEXT,
    pattern_feedback TEXT
);
-- 턴별 피드백 이전에 만들어진 DB를 위한 마이그레이션. 그때 제출된 어템프트는 attempt.feedback만 갖는다.
ALTER TABLE attempt_turn ADD COLUMN IF NOT EXISTS feedback TEXT;
-- pattern 피드백 이전에 제출된 턴은 이 값이 NULL이다.
ALTER TABLE attempt_turn ADD COLUMN IF NOT EXISTS pattern_feedback TEXT;
-- 중복 요청이 같은 턴을 두 번 쌓는 것을 막는 안전망.
-- 기존 DB에는 옛 인덱스 idx_attempt_turn_attempt가 남아 있을 수 있다(무해). 필요하면 수동으로 DROP INDEX 한다.
CREATE UNIQUE INDEX IF NOT EXISTS uq_attempt_turn_attempt_ordinal ON attempt_turn (attempt_id, ordinal);

CREATE TABLE IF NOT EXISTS turn_file_change (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id     BIGINT       NOT NULL REFERENCES attempt_turn (id) ON DELETE CASCADE,
    ordinal     INT          NOT NULL,
    path        VARCHAR(500) NOT NULL,
    change_type VARCHAR(20)  NOT NULL,
    content     TEXT
);
-- 턴별 변경 후 코드 저장 이전에 만들어진 DB를 위한 마이그레이션. DELETED는 남은 내용이 없어 NULL이다.
-- 기존 어템프트 데이터는 attempt_file이 head였던 옛 의미라 새 의미(불변 base)와 충돌하고 턴별 코드도 복원할 수 없다.
-- 그런 DB에서는 수동으로 한 번 TRUNCATE attempt CASCADE 한다.
ALTER TABLE turn_file_change ADD COLUMN IF NOT EXISTS content TEXT;
CREATE INDEX IF NOT EXISTS idx_turn_file_change_turn ON turn_file_change (turn_id, ordinal);

CREATE TABLE IF NOT EXISTS turn_tool_call (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turn_id BIGINT       NOT NULL REFERENCES attempt_turn (id) ON DELETE CASCADE,
    ordinal INT          NOT NULL,
    tool    VARCHAR(50)  NOT NULL,
    path    VARCHAR(500)
);
CREATE INDEX IF NOT EXISTS idx_turn_tool_call_turn ON turn_tool_call (turn_id, ordinal);

-- LLM API 호출 1건 = 1행. 원본 행이 진실이고 합계는 조회 시 SUM으로 파생한다.
-- 턴 연결은 (attempt_id, turn_ordinal)로 한다 — 턴이 저장되지 않은 실패 호출도 남겨야 하기 때문이다.
CREATE TABLE IF NOT EXISTS attempt_llm_call (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id          BIGINT      NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    turn_ordinal        INT,                       -- 피드백 호출·실패 flush 행은 NULL
    purpose             VARCHAR(20) NOT NULL,      -- CODE | FEEDBACK | PATTERN_FEEDBACK
    seq                 INT         NOT NULL,      -- 호출 순번(라운드). FAILED 마커는 마지막 성공 seq+1
    model               VARCHAR(100),              -- FAILED 마커 행은 NULL
    input_tokens        BIGINT,
    output_tokens       BIGINT,
    cached_input_tokens BIGINT,
    reasoning_tokens    BIGINT,
    latency_ms          BIGINT,
    cost                DECIMAL(14,8),             -- USD, 쓰기 시점 단가 스냅샷. 미등록 모델 NULL
    status              VARCHAR(20) NOT NULL,      -- SUCCESS | FAILED
    error_type          VARCHAR(50),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_attempt_llm_call_attempt ON attempt_llm_call (attempt_id, turn_ordinal, seq);

-- 실패한 CODE 호출의 사용자 프롬프트. 실패하면 턴이 저장되지 않아 입력이 어디에도 남지 않는다.
-- FEEDBACK 실패 행이 NULL인 것은 기록 누락이 아니다 — 피드백 프롬프트는 사용자가 타이핑한 값이 아니라
-- 어댑터가 problem과 attempt로 만들어내는 산출물이고, 그 입력은 어템프트에 그대로 남아 있다.
ALTER TABLE attempt_llm_call ADD COLUMN IF NOT EXISTS user_prompt TEXT;

-- 로그인 기능: 사용자 계정. 테이블명은 user가 PostgreSQL 예약어라 users를 사용한다.
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(30)              NOT NULL,
    password_hash VARCHAR(100)             NOT NULL,
    nickname      VARCHAR(30)              NOT NULL,
    email         VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL
);
-- 중복 가입 방지의 최종 안전망(서비스 계층 검사와 별개로 DB가 보장).
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_username ON users (username);
CREATE UNIQUE INDEX IF NOT EXISTS uq_users_email ON users (email);

-- 기존 어템프트는 소유자를 알 수 없으므로 NULL로 남기고, 새 코드가 생성하는 어템프트에는 user_id가 필수다.
ALTER TABLE attempt ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE attempt DROP CONSTRAINT IF EXISTS fk_attempt_user;
ALTER TABLE attempt ADD CONSTRAINT fk_attempt_user FOREIGN KEY (user_id) REFERENCES users (id);
CREATE INDEX IF NOT EXISTS idx_attempt_user ON attempt (user_id, id);
CREATE INDEX IF NOT EXISTS idx_attempt_user_submitted ON attempt (user_id, status, submitted_at DESC, id DESC);

-- 비로그인 풀이의 소유자. 쿠키 원문은 저장하지 않고 SHA-256 해시만 저장한다.
CREATE TABLE IF NOT EXISTS guest_session (
    id         UUID PRIMARY KEY,
    token_hash VARCHAR(64)              NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_guest_session_token_hash ON guest_session (token_hash);
CREATE INDEX IF NOT EXISTS idx_guest_session_expires_at ON guest_session (expires_at);

ALTER TABLE attempt ADD COLUMN IF NOT EXISTS guest_session_id UUID;
ALTER TABLE attempt DROP CONSTRAINT IF EXISTS fk_attempt_guest_session;
ALTER TABLE attempt ADD CONSTRAINT fk_attempt_guest_session
    FOREIGN KEY (guest_session_id) REFERENCES guest_session (id);
CREATE INDEX IF NOT EXISTS idx_attempt_guest_session ON attempt (guest_session_id, id);
-- 기존 배포 DB의 소유자 없는 과거 attempt 때문에 NOT VALID로 추가한다.
-- 새로 INSERT/UPDATE되는 행에는 즉시 적용되며, 과거 행을 초기화한 뒤 VALIDATE 할 수 있다.
ALTER TABLE attempt DROP CONSTRAINT IF EXISTS chk_attempt_exactly_one_owner;
ALTER TABLE attempt ADD CONSTRAINT chk_attempt_exactly_one_owner
    CHECK ((user_id IS NOT NULL AND guest_session_id IS NULL)
        OR (user_id IS NULL AND guest_session_id IS NOT NULL)) NOT VALID;

-- 어템프트 코드의 빌드/실행 요청 한 건. 결과는 buildandtest 워커가 큐로 돌려준 것을 반영한다.
CREATE TABLE IF NOT EXISTS code_run (
    id          UUID PRIMARY KEY,
    attempt_id  BIGINT      NOT NULL REFERENCES attempt (id) ON DELETE CASCADE,
    -- 어느 턴의 코드를 실행했는지. attempt_turn.ordinal과 같은 0-based 값이고,
    -- 턴을 하나도 적용하지 않은 스켈레톤 원본을 실행했으면 NULL이다.
    turn_ordinal INT,
    status      VARCHAR(20) NOT NULL,
    exit_code   INT,
    stdout      TEXT,
    stderr      TEXT,
    duration_ms BIGINT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at TIMESTAMP WITH TIME ZONE
);
-- 턴 단위 실행 이전에 만들어진 DB를 위한 마이그레이션.
-- 그때 실행된 행은 어느 턴이었는지 복원할 수 없어 NULL로 남는다.
ALTER TABLE code_run ADD COLUMN IF NOT EXISTS turn_ordinal INT;
CREATE INDEX IF NOT EXISTS idx_code_run_attempt ON code_run (attempt_id, created_at DESC);
-- 어템프트당 미완료 run은 하나만 허용한다. 동시 요청 레이스를 DB가 막아주는 안전망.
CREATE UNIQUE INDEX IF NOT EXISTS uq_code_run_active ON code_run (attempt_id) WHERE status = 'QUEUED';

-- 채점 테스트 한 건 = 1행. 워커가 JUnit XML 리포트에서 뽑아 보낸 것을 그대로 쌓는다.
-- 통과 개수를 code_run에 컬럼으로 두지 않는다 — 원본 행이 진실이고 집계는 조회 시 세어서 만든다
-- (attempt_llm_call과 같은 판단). 케이스 기록 이전에 실행된 run은 이 테이블에 행이 없고,
-- 그것은 "테스트 0개 통과"가 아니라 "기록이 없음"이다. 둘의 구분은 code_run.status가 한다.
CREATE TABLE IF NOT EXISTS code_run_case (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id      UUID         NOT NULL REFERENCES code_run (id) ON DELETE CASCADE,
    ordinal     INT          NOT NULL,   -- 리포트에 나온 순서
    class_name  VARCHAR(500),
    name        VARCHAR(500) NOT NULL,
    status      VARCHAR(20)  NOT NULL,   -- PASSED | FAILED | ERROR | SKIPPED
    message     TEXT,                    -- 실패 사유 한 줄. 통과·스킵은 NULL
    duration_ms BIGINT
);
CREATE INDEX IF NOT EXISTS idx_code_run_case_run ON code_run_case (run_id, ordinal);

CREATE TABLE IF NOT EXISTS idempotency_record (
    idempotency_key VARCHAR(128) PRIMARY KEY,
    user_id         BIGINT REFERENCES users (id),
    guest_session_id UUID REFERENCES guest_session (id),
    attempt_id      BIGINT REFERENCES attempt (id) ON DELETE CASCADE,
    status          VARCHAR(20)              NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
ALTER TABLE idempotency_record ALTER COLUMN idempotency_key TYPE VARCHAR(128);
ALTER TABLE idempotency_record ADD COLUMN IF NOT EXISTS user_id BIGINT;
ALTER TABLE idempotency_record DROP CONSTRAINT IF EXISTS fk_idempotency_record_user;
ALTER TABLE idempotency_record ADD CONSTRAINT fk_idempotency_record_user FOREIGN KEY (user_id) REFERENCES users (id);
ALTER TABLE idempotency_record ADD COLUMN IF NOT EXISTS guest_session_id UUID;
ALTER TABLE idempotency_record DROP CONSTRAINT IF EXISTS fk_idempotency_record_guest_session;
ALTER TABLE idempotency_record ADD CONSTRAINT fk_idempotency_record_guest_session
    FOREIGN KEY (guest_session_id) REFERENCES guest_session (id);
ALTER TABLE idempotency_record DROP CONSTRAINT IF EXISTS chk_idempotency_exactly_one_owner;
ALTER TABLE idempotency_record ADD CONSTRAINT chk_idempotency_exactly_one_owner
    CHECK ((user_id IS NOT NULL AND guest_session_id IS NULL)
        OR (user_id IS NULL AND guest_session_id IS NOT NULL)) NOT VALID;
CREATE INDEX IF NOT EXISTS idx_idempotency_record_user ON idempotency_record (user_id);
CREATE INDEX IF NOT EXISTS idx_idempotency_record_guest_session ON idempotency_record (guest_session_id);

-- 문제 저장소에서 마지막으로 동기화한 커밋. 한 행(id = 1)만 사용한다.
CREATE TABLE IF NOT EXISTS sync_state (
    id              BIGINT PRIMARY KEY,
    last_commit_sha VARCHAR(64)              NOT NULL,
    synced_at       TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 테스트 분리 마이그레이션의 나머지 절반(problem_test_file 생성부 참고).
-- problem_file에서 테스트를 지워도 problem_test_file로 옮겨오지는 않는다. 동기화는 커밋 SHA가
-- 움직여야 도는데 저장소는 그대로이기 때문이다. SHA를 지워 다음 주기에 전량 재동기화를 강제한다.
-- 테스트가 한 건이라도 들어오면 조건이 거짓이 되어 멈춘다(schema.sql은 부팅마다 실행된다).
-- 문제 저장소에 테스트가 하나도 없으면 매 부팅 재동기화가 도는데, 무해하고 저장소를 고치면 끝난다.
DELETE FROM sync_state WHERE NOT EXISTS (SELECT 1 FROM problem_test_file);

-- 랭킹이 "모두를 같은 자로" 재려면 단가가 SQL 안에 있어야 한다. 진실은 여전히
-- application.yml의 llm.pricing이고 이 테이블은 부팅 때 동기화되는 사본이다
-- (problem을 GitLab에서 동기화해 두는 것과 같은 관계).
-- 모델당 한 행이고 이력은 두지 않는다 — 과거 시점 재현은 attempt_llm_call.cost에 이미 박혀 있다.
CREATE TABLE IF NOT EXISTS model_price (
    model        VARCHAR(100) PRIMARY KEY,
    input        DECIMAL(12,6) NOT NULL,  -- 100만 토큰당 USD
    cached_input DECIMAL(12,6),           -- NULL이면 input 단가를 적용한다
    output       DECIMAL(12,6) NOT NULL,
    updated_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

-- 랭킹은 문제 하나의 제출을 전부 훑는다. attempt.problem_id에는 FK만 있고 인덱스가 없었다
-- (PostgreSQL은 FK에 인덱스를 자동 생성하지 않는다).
CREATE INDEX IF NOT EXISTS idx_attempt_problem_status ON attempt (problem_id, status);
-- 자격 판정이 (attempt_id, turn_ordinal, status)로 SUCCEEDED 실행을 찾는다.
CREATE INDEX IF NOT EXISTS idx_code_run_attempt_turn_status ON code_run (attempt_id, turn_ordinal, status);

-- 릴레이 게임 방 하나. 여러 사람이 한 문제를 정해진 순서대로 이어 푼다.
-- 코드 진화(프롬프트·생성 코드·파일 변경·채점)는 attempt_id가 가리키는 어템프트가 담당하고,
-- 이 테이블은 방·순서·진행 단계만 들고 있다. 자세한 판단은 docs/relay-game-plan.md 참고.
CREATE TABLE IF NOT EXISTS relay_room (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- 방장이 붙이는 방 이름. 개설 API는 필수로 받지만, 이름 도입 전에 만들어진 행이
    -- 있어 컬럼은 NULL을 허용한다(아래 마이그레이션 참고). 화면이 방 번호로 대신한다.
    name               VARCHAR(30),
    problem_id         BIGINT      NOT NULL REFERENCES problem (id),
    host_user_id       BIGINT      NOT NULL REFERENCES users (id),
    -- 게임 시작 시점에 만든다. WAITING 동안은 NULL이다.
    attempt_id         BIGINT      REFERENCES attempt (id),
    status             VARCHAR(30) NOT NULL,
    total_laps         INT         NOT NULL,
    max_participants   INT         NOT NULL,
    -- 시작 시 확정한 참가자 수. 이후 이탈해도 좌석 수는 변하지 않는다.
    seat_count         INT,
    -- 릴레이 진행 인덱스. 좌석은 seat_count로 나눈 나머지, 바퀴는 몫이다.
    -- 좌석과 바퀴를 따로 저장하면 둘이 어긋날 수 있어 단일 카운터에서 파생한다.
    current_turn_index INT         NOT NULL DEFAULT 0,
    turn_deadline      TIMESTAMP WITH TIME ZONE,
    -- 진행 중인 채점 run. 워커 결과 이벤트를 이 값으로 방에 되돌려 잇는다.
    current_run_id     UUID,
    -- 시작 스켈레톤의 채점. 첫 주자의 점수(증가분)를 재는 기준선이다 — 스켈레톤이 이미
    -- 통과시키는 테스트가 있으면 기준선 없이는 첫 주자 점수가 부풀려진다.
    -- 시작 시점에 비동기로 요청하므로 결과가 오기 전까지 passed/total은 NULL이다.
    baseline_run_id    UUID,
    baseline_passed    INT,
    baseline_total     INT,
    created_at         TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at         TIMESTAMP WITH TIME ZONE,
    finished_at        TIMESTAMP WITH TIME ZONE
);
CREATE INDEX IF NOT EXISTS idx_relay_room_status ON relay_room (status, created_at DESC);
-- 베이스라인 채점 이전 버전으로 만들어진 개발 DB를 위한 마이그레이션.
ALTER TABLE relay_room ADD COLUMN IF NOT EXISTS baseline_run_id UUID;
ALTER TABLE relay_room ADD COLUMN IF NOT EXISTS baseline_passed INT;
ALTER TABLE relay_room ADD COLUMN IF NOT EXISTS baseline_total INT;
-- 방 이름 이전 버전으로 만들어진 개발 DB를 위한 마이그레이션.
ALTER TABLE relay_room ADD COLUMN IF NOT EXISTS name VARCHAR(30);

-- 방 참가자. seat_order는 입장 시점이 아니라 게임 시작 시점에 joined_at 순으로 부여한다 —
-- 시작 전 이탈 때문에 좌석 번호를 재정렬할 일이 없어진다.
CREATE TABLE IF NOT EXISTS relay_participant (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id    BIGINT NOT NULL REFERENCES relay_room (id) ON DELETE CASCADE,
    user_id    BIGINT NOT NULL REFERENCES users (id),
    seat_order INT,
    joined_at  TIMESTAMP WITH TIME ZONE NOT NULL,
    -- 게임 중 이탈 시각. 좌석은 유지되고 그 좌석의 턴은 제한시간 뒤 스킵된다.
    left_at    TIMESTAMP WITH TIME ZONE
);
-- 같은 사람이 한 방에 두 번 들어갈 수 없다. 동시 입장 레이스의 안전망.
CREATE UNIQUE INDEX IF NOT EXISTS uq_relay_participant_user ON relay_participant (room_id, user_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_relay_participant_seat ON relay_participant (room_id, seat_order)
    WHERE seat_order IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_relay_participant_room ON relay_participant (room_id, joined_at);

-- "몇 번째 릴레이 턴을 누가 썼는가"만 기록하는 사이드카. 프롬프트·생성 코드·파일 변경은
-- 방의 어템프트(attempt_turn)에 있고, attempt_turn_ordinal로 이어붙는다.
CREATE TABLE IF NOT EXISTS relay_turn (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id              BIGINT NOT NULL REFERENCES relay_room (id) ON DELETE CASCADE,
    -- 릴레이 진행 인덱스(0-based). 스킵된 턴도 번호를 차지한다.
    turn_index           INT    NOT NULL,
    author_user_id       BIGINT NOT NULL REFERENCES users (id),
    -- 대응하는 attempt_turn.ordinal. 스킵(타임아웃·이탈)이면 NULL이다.
    -- 스킵이 생기면 turn_index와 어긋나므로 둘을 따로 들고 있어야 한다.
    attempt_turn_ordinal INT,
    -- 이 턴 직후의 채점. 결과 원본은 code_run/code_run_case에 있고 여기엔 참조와 집계만 둔다.
    -- 집계를 굳이 복사하는 이유: 점수가 "직전 턴 대비 증가분"이라 턴마다 확정값이 남아야 한다.
    run_id               UUID,
    passed_count         INT,
    total_count          INT,
    started_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    finished_at          TIMESTAMP WITH TIME ZONE
);
CREATE UNIQUE INDEX IF NOT EXISTS uq_relay_turn_index ON relay_turn (room_id, turn_index);
